### ISSUE TITLE
CI is failing!

### ISSUE THREAD

**Issue by sils** [coala/coala-atom#24]
Heeeelp! Apparently the plugin doesn't work anymore?

CC @AbdealiJK

**Comment by sils** [comment]
CC @tushar-rishav as well

**Comment by chocobn69** [comment]
Hi, first time trying and doesn't work

Atom 1.12.2
plugin coala 0.2.0
coala 0.8.1

**Comment by sils** [comment]
Would you be interested in looking into this?

IIUC atom did an atom and now like every second plugin is broken, at least that was the feeling one of the guys I met at a meetup had.

**Comment by chocobn69** [comment]
I just upgraded to 1.12.3 (archlinux) and it's ok now

**Comment by sils** [comment]
So it was a bug in atom?

**Comment by chocobn69** [comment]
I think it was just coala-format slow execution. Maybe I miss something
in my .coafile

**Comment by chocobn69** [comment]
Yes, I just limited coala files param to my code only (and not my venv) and it became ok

**Comment by jayvdb** [comment]
I think it is because `coala-format` is deprecated
See my [build log](https://circleci.com/gh/jayvdb/coala-atom/1).

**Comment by jayvdb** [comment]
https://github.com/coala/coala-atom/pull/25 looks like it will fix it.

**Comment by RohanVB** [comment]
> https://github.com/coala/coala-atom/blob/master/lib/main.coffee#L52

This was fixed. The plugin doesn't use `coala-format` anymore. 
I don't get why #25 was closed and not merged. Most of the changes made in it were reflected, there's no PR reference. Relevant commit is: a4963716c071712ae1664ad6f7558cba89a4413b
CC @jayvdb @sils 

Also, since the backport was done: https://github.com/coala/coala/pull/3381
Now we want to remove the deprecated version from coala, which is no longer being used in atom. (See above link in quote)
If this is fine, then from coala-atom https://github.com/coala/coala/pull/3426 should be good to go. 
Reference of coala-atom: [January 22, 2017 8:49 PM](https://gitter.im/coala/coala?at=5884cd8d519afee26b9a2df6)

**Comment by RohanVB** [comment]
Corresponding issues linked to this issue have been fixed. Further issues on CircleCI here (if any remain after rebuild): https://github.com/coala/coala-atom/issues/38
