### ISSUE TITLE
Add useful info in README

### ISSUE THREAD

**Issue by sils** [coala/coala-atom#3]
@AbdealiJK at least installation commands and an example usage would _really_ be needed!

**Comment by AbdealiLoKo** [comment]
Yeah, I don't have a laptop right now (travelling). I'll do it within a few days.

-----Original Message-----

**Comment by sils** [comment]
done

**Comment by sils** [comment]
@AbdealiJK isn't it smarter to install with `apm link .` or so?

**Comment by AbdealiLoKo** [comment]
Apm link would just make a symlink to the packages folder in atom right?

If a person downloads the git repo to Downloads and runs that. Then if he deleted the repo from Downloads then the symlink would be broken. Hence I don't like that method very much.

Is there a method to automatically copy the folder there rather than link it? I don't recall finding a command for that

-----Original Message-----

**Comment by sils** [comment]
There is apm install but it doesn't work I think.

2016-01-29 14:16 GMT+01:00 AbdealiJK notifications@github.com:
