### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by sils** [coala/coala-atom#8]
we should fix the coala version for plugins

**Comment by AbdealiLoKo** [comment]
You mean specify installing coala 0.4.0 in the README and requirements.txt ?

**Comment by sils** [comment]
only in the requirements.txt IMO, in the readme just tell the user to do `pip3 -r requirements.txt` otherwise we'll forget to change it at both places

**Comment by AbdealiLoKo** [comment]
I'm thinking this is a bad way to do it because atom has a GUI and most
users shouldn't be forced to go into ~/.atom/packages and so on.

I think the better way is to throw an error inside atom if:
- the `coala` executable is not found
- the coala executable with arg --version gives a version lower than 0.4.0

**Comment by AbdealiLoKo** [comment]
i.e. https://github.com/coala-analyzer/coala-atom/issues/7 would be a better solution that this.

**Comment by sils** [comment]
ok neat
